---

- name: Get variables for OS
  include_vars: "{{ item }}"
  with_items: "{{ ansible_distribution | lower }}.yml"

- name: "Remove old versions of Docker"
  package:
    name: "{{ docker-packages-remove }}"
    state: absent

- name: "Docker repository - {{ ansible_distribution }}"
  include_tasks: "docker-repo-{{ ansible_distribution | lower }}.yml"

- name: "Install docker package(s)"
  package:
    name: "{{ docker-packages-install }}"
    state: latest

# This task will error out if the user doesn't exist
- name: "Check to see if the targeted docker user exists"
  command: id "{{ docker_username }}"
  changed_when: false

- name: "Add Docker group"
  group:
    name: docker
    state: present

- name: "Add username to the Docker group"
  user:
    name: "{{ docker_username }}"
    groups: "docker"
    append: yes

- name: "Enable Docker"
  service:
    name: docker
    enabled: yes
    state: started
