---
- name: "Remove old versions of Docker"
  dnf:
    name: 
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent

- name: "Enable Docker repository"
  yum_repository:
    name: docker-ce-stable
    description: "Docker CE Stable - x86_64"
    file: docker-ce.repo
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/stable"
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg

- name: "Install docker package(s)"
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: "Enable docker"
  service:
    name: docker
    enabled: yes
    state: started

# This task will error out if the user doesn't exist
- name: "Check to see if the targeted docker user exists"
  command: id "{{ docker_username }}"
  changed_when: false

- name: "Add docker group"
  group:
    name: docker
    state: present
  notify: 
  - restart docker

- name: "Add username to the docker group" 
  user:
    name: "{{ docker_username }}"
    groups: docker
    append: yes

