---

- block: # become: True

  - name: "install epel-release"
    package:
      name: "{{ ansible_tower_epel_download_url }}"
      state: present

  - name: "Download & Unpack Ansible Tower installer"
    unarchive:
      src: "{{ ansible_tower_download_url }}"
      dest: "."
      list_files: true
      remote_src: true
      exclude: "inventory"
    register: ansible_tower_download_fact

  - name: "Set installation facts"
    set_fact:
      # The first file listed in the output of the unarchiving from downloading tower
      # is the directory so set that as ansible_tower_dir
      ansible_tower_dir: "{{ ansible_tower_download_fact.files.0 }}"
      # Need to check if version 3.7 or later as we use different inventory values
      ansible_tower_37_later: "{{ (ansible_tower_version is version(3.7, '>=')) or (ansible_tower_version == 'latest') }}"

  - name: "Set up the Ansible Tower inventory"
    template:
      src: inventory.j2
      dest: "{{ ansible_tower_dir }}/inventory"
    register: inventory

  - name: "run tower installer"
    shell: ./setup.sh
    args:
      chdir: "{{ ansible_tower_dir }}"

  - name: "Download 'oc' client for OpenShift interactions"
    get_url:
      url: "{{ ansible_tower_oc_download_url }}"
      dest: /tmp/
    register: oc_download
    when:
    - ansible_tower_oc_download_url|trim != ''

  - name: "Extract 'oc' client to /bin"
    unarchive:
      src: "{{ oc_download.dest }}"
      dest: /bin
      remote_src: True
    when:
    - ansible_tower_helm_download_url|trim != ''
    - oc_download.dest

  - name: "Download 'helm' client for Helm Charts"
    get_url:
      url: "{{ ansible_tower_helm_download_url }}"
      dest: /tmp/
    register: helm_download
    when:
    - ansible_tower_helm_download_url|trim != ''

  - name: "Extract 'helm' client to a temporary location"
    unarchive:
      src: "{{ helm_download.dest }}"
      dest: /tmp
      remote_src: True
      list_files: True
    register: helm_extract
    when:
    - ansible_tower_helm_download_url|trim != ''
    - helm_download.dest

  - name: "Move the 'helm' binary to /bin"
    copy:
      src: "/tmp/{{ item }}"
      dest: /bin/
      follow: yes
      mode: '755'
      remote_src: True
    with_items: "{{ helm_extract.files | map('regex_search','.*helm') | select('string') | list }}"
    when:
    - ansible_tower_helm_download_url|trim != ''
    - helm_download.dest
    - helm_extract.files

  become: True
