---
docker_packages_remove: docker,docker-client,docker-client-latest,docker-common,docker-latest,docker-latest-logrotate,docker-logrotate,docker-engine
docker_packages_install: docker-ce,docker-ce-cli,containerd.io
